name: Week5-CI-CD

on:
  push:
    branches:
      - Week5

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install npm
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build Docker image
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops_naukma_week5:latest

      - name: Login and push to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - run: docker push riperyt/devops_naukma_week5:latest
