name: Week5-CI-CD

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install npm
        run: npm install

      - name: Lint code
        run: npm run lint
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: devops_naukma_week5:latest

      - name: Push push to Docker Hub
        if: success()
        run: |
          docker tag devops_naukma_week5:latest riperyt/devops_naukma_week5:latest
          docker push riperyt/devops_naukma_week5:latest
          
      - name: Test Docker image
        if: success()
        run: |
          docker run -d -p 80:80 riperyt/devops_naukma_week5
          sleep 5
          curl http://localhost:80/
